config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :employers, :controllers => { registrations: 'registrations' }

  resources :job_posts
  resources :payments

  root to: "job_posts#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :job_posts

  validates :name, presence: true
end

app/models/job_category.rb
class JobCategory < ActiveRecord::Base
  has_many :job_posts

  scope :with_jobs, -> {
    joins("INNER JOIN job_posts ON job_posts.job_category_id = job_categories.id").
    group("job_categories.id")
  }
end

app/models/job_post.rb
class JobPost < ActiveRecord::Base
  belongs_to :employer
  belongs_to :job_category

  has_one :payment

  validates :title, presence: true
  validates :summary, presence: true
  validates :description, presence: true
  validates :compensation, presence: true
  validates :apply, presence: true

  scope :unpaid, -> {
    joins("LEFT JOIN payments ON job_posts.id = payments.job_post_id").
    group("job_posts.id").
    having("COUNT(payments.id) = 0").
    last
  }

  def employer_name
    employer && employer.name
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :job_post

  before_save :save_amount

  def amount_in_cents
    total * 100
  end

  def total
    (featured? ? featured_cost : 0) + base_cost
  end

  def featured?
    job_post && job_post.featured?
  end

  def featured_cost
    50
  end

  def base_cost
    200
  end

  def capture(token)
    begin
      customer = Stripe::Customer.create email: job_post.employer.email,
                                         card: token
      charge = Stripe::Charge.create customer: customer.id,
                                     amount: amount_in_cents,
                                     description: "Diversity Job Posting",
                                     currency: 'usd'
      update_attributes(auth_code: charge.id)
    rescue
      false
    end
  end

private

  def save_amount
    write_attribute(:amount, total)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  before_action :authenticate_employer!, except: %i[index show]

  def index
  end

  def show
    job_post
  end

  def new
    new_job_post
  end

  def create
    if new_job_post(job_post_params).save
      redirect_to new_payment_path
    else
      render :new
    end
  end

private

  def job_post
    @job_post ||= JobPost.find(params[:id])
  end

  def new_job_post(attrs={})
    @job_post ||= current_employer.job_posts.new(attrs)
  end

  def job_post_params
    params.require(:job_post).permit(:title, :job_category_id, :summary,
                                     :description, :compensation,
                                     :apply)
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_employer!

  def new
    @job_post = current_employer.job_posts.unpaid
    @payment = @job_post.build_payment
  end

  def create
    @job_post = current_employer.job_posts.unpaid
    @payment = @job_post.build_payment
    if @payment.capture(params["stripeToken"])
      redirect_to :root
    else
      render :new
    end
  end

private

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:employer).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:employer).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/job_posts/_form.html.erb
<%= form_for(@job_post) do |f| %>
  <% if @job_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_post.errors.count, "error") %> prohibited this job from being posted:</h2>

      <ul>
      <%- @job_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="checkbox featured">
      <label><%= f.check_box :featured? %>
      Display your post with a highlighted background for $50 more</label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, value: "Job Posting Title" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :job_category %>
    <span class="form-group">
      <%= f.collection_select :job_category_id, JobCategory.all, :id, :name, {}, class: 'form-control' %>
    </span>
  </div>
  <div class="form-group">
    <%= f.label :summary, value: "Describe the position in brief" %>
    <%= f.text_area :summary, rows: 4, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, value: "Describe the position in detail" %>
    <%= f.text_area :description, rows: 8, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :compensation, "Describe the compensation offered:" %>
    <%= f.text_area :compensation, rows: 4,  class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :apply, "How would a person apply for this awesome job?" %>
    <%= f.text_area :apply,  rows: 4, class: 'form-control' %>
  </div>

  <div class="actions">
    <div class="pull-right">
    <%= f.submit "Continue to payment", class: 'btn btn-primary btn-lg' %> or go
    <%= link_to 'back', job_posts_path %>
    </div>
    <div class="clearfix"></div>
  </div>
<% end %>

app/views/job_posts/_posting_li.html.erb
<li class="posting <%= 'featured' if job.featured? %>">
  <%= link_to job, class: "job-title-index" do %>
    <span class="employer-name">
      <%= job.employer_name %>
    </span>
    <%= job.title %>
  <% end %>
  <span class="job-date"><%= job.created_at.strftime("%b %e") %></span>
  <div class="clearfix"></div>
</li>

app/views/job_posts/edit.html.erb
<h1>Editing Job Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_post %> |
<%= link_to 'Back', job_posts_path %>

app/views/job_posts/index.html.erb
<div class="job-posts">
<% JobCategory.with_jobs.each do |jc| %>
  <div class="job-post">
    <div class="heading">
      <div class="post-job pull-right">
        <a class="btn btn-primary new-btn" href="#" data-category-id="<%= jc.id %>">Post a <%= jc.name.downcase %> job: $200 for 30 days</a>
      </div>

      <h2><%= jc.name %> Jobs</h2>
      <div class="clearfix"></div>
    </div>

    <ul class="list-unstyled">
      <% jc.job_posts.each do |job| %>
        <%= render partial: 'posting_li', locals: { job: job } %>
      <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/job_posts/new.html.erb
<div class="new-job-post">
  <div class="row">
    <h1>Create a new diversity job posting (30 days)</h1>
  </div>

  <div class="row">
    <%= render 'form' %>
  </div>

</div>

app/views/job_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job_post.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @job_post.summary %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job_post.description %>
</p>

<p>
  <strong>Compensation:</strong>
  <%= @job_post.compensation %>
</p>

<p>
  <strong>Apply:</strong>
  <%= @job_post.apply %>
</p>

<%= link_to 'Edit', edit_job_post_path(@job_post) %> |
<%= link_to 'Back', job_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobs for Diverse and Talented People! | diversityjobs.io</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">diversityjobs.io</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>

          <% if employer_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to('Edit', edit_employer_registration_path) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to('Logout', destroy_employer_session_path, :method => :delete) %></li>
            </ul>
          </li>
          <% else %>
          <li>
            <%= link_to('Login', new_employer_session_path)  %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="col-sm-12">
      <div class="row">
        <%=  yield %>
      </div>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/payments/new.html.erb
<%= form_for @payment, html: { class: "basic-grey" } do |f| %>
  <h2>Your job post will run for 30 days</h2>
  <h3>Paying today: <%= number_to_currency(200) %></h3>

  <div class="job_post">
    <h2><%= @job_post.title %></h2>
    <h3>Job Summary</h3>
    <div><%= @job_post.summary %></div>

    <h3>Description</h3>
    <div><%= @job_post.description %></div>

    <h3>Compensation</h3>
    <div><%= @job_post.compensation %></div>

    <h3>How to apply</h3>
    <div><%= @job_post.apply %></div>
  </div>

  <script class="stripe-button"
          data-amount="<%= @payment.amount_in_cents %>"
            data-description="Diversity Job Posting"
            data-key="<%=ENV.fetch("STRIPE_PUBLISHABLE_KEY") %>"
            src="https://checkout.stripe.com/checkout.js"></script> 
<%- end %>